packages:
  - "extension"
onlyBuiltDependencies:
  - esbuild
  - workerd
ignoredBuiltDependencies:
  - core-js
  - protobufjs
  - sharp
  - unrs-resolver

allowBuilds:
  core-js: false
  esbuild: true
  protobufjs: false
  sharp: false
  unrs-resolver: false
  workerd: true
